### PR TITLE
Parse SPDX: manage relations with top level package

### LINKED ISSUE #1102: [ingestion/data-quality issue] SPDX SBOM IsDependencyIngest not created
**Describe the bug**
A IsDependencyIngest object is not created when dealing with an SPDX SBOM for a container with `CONTAINED_BY` relations and a single `DESCRIBES` relationship.

**To Reproduce**

1. `./bin/guacgql`
1. `./bin/guacone collect files <JSON_Ingested_document_below>`
1. check output
```
{"level":"info","ts":1690555042.183181,"caller":"helpers/bulk.go:34","msg":"assembling Package: 1"}
[...]
{"level":"info","ts":1690555042.1878204,"caller":"helpers/bulk.go:123","msg":"assembling IsDependency: 0"}
[...]
{"level":"info","ts":1690555042.187917,"caller":"helpers/bulk.go:192","msg":"assembling HasSBOM: 1"}
[...]
{"level":"info","ts":1690555042.1890552,"caller":"cmd/files.go:217","msg":"completed ingesting 1 documents of 1"}
```

I'm going to open a PR sharing a test to reproduce this issue.

**Expected behavior**
The 2 packages and their dependency relation should be created meaning the log should have reported

- `assembling Package: 2`
- `assembling IsDependency: 1`

**GUAC version**
Latest main branch (i.e. c3fe7c4eef4e7e304a29885210bf3034b6fff1b9)

**Ingested document(s)**

```
{
   "SPDXID":"SPDXRef-DOCUMENT",
   "spdxVersion":"SPDX-2.2",
   "documentDescribes":[
      "SPDXRef-6dcd47a4-bfcb-47d7-8ee4-60b6dc4861a8"
   ],
   "documentNamespace": "https://access.redhat.com/security/data/sbom/beta/spdx/ubi9-container-6dcd47a4-bfcb-47d7-8ee4-60b6dc4861a8",
   "name":"sbom-sha256:a743268cd3c56f921f3fb706cc0425c8ab78119fd433e38bb7c5dcd5635b0d10",
   "packages":[
      {
         "SPDXID":"SPDXRef-8c5bc68a-d747-48de-b737-bc9703c330e7",
         "externalRefs":[
            {
               "referenceCategory":"PACKAGE_MANAGER",
               "referenceLocator":"pkg:rpm/redhat/python3-libcomps@0.1.18-1.el9?arch=x86_64",
               "referenceType":"purl"
            }
         ],
         "packageFileName":"python3-libcomps-0.1.18-1.el9.x86_64.rpm",
         "versionInfo":"python3-libcomps-0.1.18-1.el9.x86_64"
      },
      {
         "SPDXID":"SPDXRef-6dcd47a4-bfcb-47d7-8ee4-60b6dc4861a8",
         "externalRefs":[
            {
               "referenceCategory":"PACKAGE_MANAGER",
               "referenceLocator":"pkg:oci/redhat/ubi9-container@sha256:4227a4b5013999a412196237c62e40d778d09cdc751720a66ff3701fbe5a4a9d?repository_url=registry.redhat.io/ubi9&tag=9.1.0-1750",
               "referenceType":"purl"
            }
         ],
         "name":"ubi9-container",
         "versionInfo":"ubi9-container-9.1.0-1750.noarch"
      }
   ],
   "relationships":[
      {
         "relatedSpdxElement":"SPDXRef-6dcd47a4-bfcb-47d7-8ee4-60b6dc4861a8",
         "relationshipType":"CONTAINED_BY",
         "spdxElementId":"SPDXRef-8c5bc68a-d747-48de-b737-bc9703c330e7"
      },
      {
         "relatedSpdxElement":"SPDXRef-6dcd47a4-bfcb-47d7-8ee4-60b6dc4861a8",
         "relationshipType":"DESCRIBES",
         "spdxElementId":"SPDXRef-DOCUMENT"
      }
   ]
}
```
**Additional context**
I'm going to open a PR sharing a test to reproduce this issue and also with a fix for this to be discussed.

### PR DESCRIPTION
**Pull request by mrizzi**
# Description of the PR
It looks like the `GetPredicates` method isn't able to create the `IsDependencyIngest` object because the `foundPackNodes := s.getPackageElement(foundId)` is always `nil` due to `getPackageElement` only searches in `packagePackages` map but the package, with current code, is available only in the `topLevelPackages` map (and with the `DOCUMENT` key).

Removing the `else` and so always adding the top packages to the `packagePackages` lets `getPackageElement` to find the top package and hence created the expected `IsDependencyIngest` object.

Fixes #1102 

# PR Checklist

- [] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [x] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Review by pxp928 — COMMENTED** [review]
Is this missing the SPDX parser update?

**Comment by mrizzi** [comment]
> Is this missing the SPDX parser update?

I was pushing the fix in the next commit so that the reproducer would have run showing the issue from the test and the later commit would have fixed the broken test.

And, tbh, I've already pushed the "fixing" commit (ref. https://github.com/guacsec/guac/compare/main...mrizzi:guac:issue-1102) but it looks like the PR isn't updated.

**Comment by mrizzi** [comment]
@pxp928 as I mentioned, the first commit added just the test reproducer of the issue reported:
```go
=== RUN   Test_spdxParser/SPDX_with_documentDescribes_field
    parse_spdx_test.go:346: spdx.GetPredicate mismatch values (+got, -expected):   &assembler.IngestPredicates{
          	CertifyScorecard: nil,
        - 	IsDependency: []assembler.IsDependencyIngest{
        - 		{
        - 			Pkg: &generated.PkgInputSpec{
        - 				Type:      "oci",
        - 				Namespace: &"registry.redhat.",
        - 				Name:      "ubi9-container",
        - 				Version:   &"sha256:4227a4b5013999a412196237c"...,
        - 				...
        - 			},
        - 			DepPkg: &generated.PkgInputSpec{
        - 				Type:      "rpm",
        - 				Namespace: &"redhat",
        - 				Name:      "python3-libcomps",
        - 				Version:   &"0.1.18-1.el9",
        - 				...
        - 			},
        - 			IsDependency: &generated.IsDependencyInputSpec{
        - 				VersionRange:   "0.1.18-1.el9",
        - 				DependencyType: "UNKNOWN",
        - 				Justification:  "Derived from SPDX CONTAINED_BY r"...,
        - 			},
        - 		},
        - 	},
        + 	IsDependency: nil,
          	IsOccurrence: nil,
          	HasSlsa:      nil,
          	... // 10 identical fields
          }
```
Where it's clear the dependency hasn't been created.
Then the second commit, the one with the fix, ran successfully the tests.

File: pkg/ingestor/parser/spdx/parse_spdx.go [hunk 1]
```diff
@@ -123,9 +123,8 @@ func (s *spdxParser) getPackages() error {
 
 		if slices.Contains(topLevelSpdxIds, string(pac.PackageSPDXIdentifier)) {
```
Comment (pxp928) [inline pkg/ingestor/parser/spdx/parse_spdx.go:124]: This looks good but does this check for the `getTopLevelPackageSpdxIds` need to be changed? @lumjjb?

https://github.com/guacsec/guac/blob/07353d5563c6690415225c8b96ee388e0e98317f/pkg/ingestor/parser/spdx/parse_spdx.go#L89-L93

Comment (mrizzi) [reply pkg/ingestor/parser/spdx/parse_spdx.go:124]: AFAIU, this looks good as it's properly "contributing" to the `HasSBOM` predicate's creation during SBOM ingestion.
But obviously @lumjjb knows better.

At the same time, the issue and the fix here are more towards let the `getPackageElement` func to work properly since it's the one in charge of finding the `{found,related}PackNodes` values and this feature is based only searching within the `packagePackages` map.

I hope this helps.

Comment (pxp928) [reply pkg/ingestor/parser/spdx/parse_spdx.go:124]: Just did some testing to understand. Looks good.

**Review by pxp928 — APPROVED** [review]

**Review by lumjjb — APPROVED** [review]
LGTM! Good catch @mrizzi

**Comment by lumjjb** [comment]
FYI: @CrossedSecurity if you're interested.
