### PR TITLE
removing MAX_CONCURRENT_JOBS

### LINKED ISSUE #1433: [bug] MAX_CONCURRENT_JOBS is no longer being used
**Describe the bug**
The environment variable `"MAX_CONCURRENT_JOBS"` is no longer being utilized in [guacone collect files](https://github.com/guacsec/guac/blob/main/cmd/guacone/cmd/files.go#L44). This was utilized to allow the concurrency and allow the backend to process multiple files simultaneously. This functionality was removed in: https://github.com/guacsec/guac/pull/1195

**To Reproduce**

1. set `export MAX_CONCURRENT_JOBS=3`
2. run `go run ./cmd/guacone collect files ../guac-data/top-dh-sboms`

**Expected behavior**
Based on the value set for `MAX_CONCURRENT_JOBS`, it should concurrently try to ingest multiple documents 

**GUAC version**
main and v0.3.0

### PR DESCRIPTION
**Pull request by arorasoham9**
# Description of the PR

Removing MAX_CONCURRENT_JOBS option

Attempt to fix #1433

# PR Checklist

- [ ] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

File: cmd/guacone/cmd/files.go [hunk 1]
```diff
@@ -126,17 +123,7 @@ var filesCmd = &cobra.Command{
...
-		if found {
-			jobs, err := strconv.Atoi(maxConcurrentJobs)
-			if err != nil {
-				logger.Fatalf("failed to convert concurrent jobs value to integer ")
-			}
-			files.SetLimit(jobs)
-		} else {
-			files.SetLimit(1)
-		}
+		files.SetLimit(1)
```
Comment (pxp928) [inline cmd/guacone/cmd/files.go:126]: Can remove all this completely. `files, filesCtx := errgroup.WithContext(ctx)` and replace with the regular `ctx`

**Review by pxp928 — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]
