### PR TITLE
fix queryVulnsViaVulnNodeNeighbors to check for certifyVex edges

### LINKED ISSUE #1539: [bug] `guacone query vuln` does not return VEX statements when a vulnerability ID is passed in
**Describe the bug**
When running `guacone query vuln <purl> --vuln-id <vuln-id>`, the table output does not show any related VEX statements when they are present. However, if you were to run `guacone query vuln <purl>` without a vulnerability ID, related VEX statements are returned.

**To Reproduce**

1. Collect a SBOM that contains dependencies with vulnerabilities
2. Collect a VEX statement using a vulnerability ID that is present in the SBOM
``` json
{
  "@context": "https://openvex.dev/ns",
  "@id": "https://openvex.dev/docs/public/vex-88f73742d154e9e356788e7e475effd622c4fb18c3955a523319c34c7d2b6da6",
  "author": "Unknown Author",
  "role": "Document Creator",
  "timestamp": "2023-11-16T22:34:40.160264197Z",
  "version": 1,
  "statements": [
    {
      "vulnerability": {
        "name": "ghsa-4374-p667-p6c8"
      },
      "products": [
        {
          "@id": "pkg:swid/MySBOMDocument"
        }
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path"
    }
  ]
}
```
3. Run `guacone query vuln pkg:swid/MySBOMDocument --vuln-id ghsa-4374-p667-p6c8`
4. Observer that there is no VEX statement returned as a table row

**Expected behavior**
VEX statements should always be returned, regardless of whether a vulnerability ID is passed in.

**GUAC version**
Latest on main

**Additional context**
Will update the description with a better test case if I find one. I discovered the bug on an internal SBOM.

### PR DESCRIPTION
**Pull request by ridhoq**
# Description of the PR

`queryVulnsViaVulnNodeNeighbors` now searches for `certifyVex` edges 

Fixes #1539 

# PR Checklist

- [ ] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

File: cmd/guacone/cmd/vulnerability.go [hunk 1]
```diff
@@ -329,11 +332,16 @@ func searchDependencyPackages(ctx context.Context, gqlclient graphql.Client, top
...
-func queryVulnsViaVulnNodeNeighbors(ctx context.Context, gqlclient graphql.Client, topPkgResponse *model.PackagesResponse, vulnerabilityNodeID string, edgeType model.Edge, depth, pathsToReturn int) ([]string, error) {
+func queryVulnsViaVulnNodeNeighbors(ctx context.Context, gqlclient graphql.Client, topPkgResponse *model.PackagesResponse, vulnerabilityNodeID string, edgeType model.Edge, depth, pathsToReturn int) ([]string, []table.Row, error) {
 	var path []string
+	var tableRows []table.Row
 	vulnNodeNeighborResponse, err := model.Neighbors(ctx, gqlclient, vulnerabilityNodeID, []model.Edge{edgeType})
 	if err != nil {
-		return nil, fmt.Errorf("error querying neighbor for vulnerability: %w", err)
+		return nil, []table.Row{}, fmt.Errorf("error querying neighbor for vulnerability: %w", err)
+	}
+	pkgVersionNeighborResponse, err := model.Neighbors(ctx, gqlclient, topPkgResponse.Packages[0].Namespaces[0].Names[0].Versions[0].Id, []model.Edge{model.EdgePackageCertifyVexStatement})
```
Comment (ridhoq) [inline cmd/guacone/cmd/vulnerability.go:342]: This was a hack I did to unblock myself, but would like feedback about what we should actually do here

File: cmd/guacone/cmd/vulnerability.go [hunk 2]
```diff
@@ -329,11 +332,16 @@ func searchDependencyPackages(ctx context.Context, gqlclient graphql.Client, top
 	return path, tableRows, nil
 }
 
-func queryVulnsViaVulnNodeNeighbors(ctx context.Context, gqlclient graphql.Client, topPkgResponse *model.PackagesResponse, vulnerabilityNodeID string, edgeType model.Edge, depth, pathsToReturn int) ([]string, error) {
+func queryVulnsViaVulnNodeNeighbors(ctx context.Context, gqlclient graphql.Client, topPkgResponse *model.PackagesResponse, vulnerabilityNodeID string, edgeType model.Edge, depth, pathsToReturn int) ([]string, []table.Row, error) {
 	var path []string
+	var tableRows []table.Row
 	vulnNodeNeighborResponse, err := model.Neighbors(ctx, gqlclient, vulnerabilityNodeID, []model.Edge{edgeType})
```
Comment (pxp928) [inline cmd/guacone/cmd/vulnerability.go:338]: so you dont need to get the neighbors from the package. You could just get it from the vulnerability. So along with `certifyVuln`, you can add `model.EdgeVulnerabilityCertifyVexStatement` here

File: cmd/guacone/cmd/vulnerability.go (hunk 1 above)
Comment (pxp928) [reply cmd/guacone/cmd/vulnerability.go:342]: no need for this, see the comment above. This can be done from neighbors from the vulnerability

**Review by pxp928 — COMMENTED** [review]
Almost on the right path :). Thanks for the PR!

**Comment by pxp928** [comment]
let me know if that makes sense, I can elaborate more if needed.

**Comment by pxp928** [comment]
@ridhoq can you rebase this? Thanks!

**Comment by ridhoq** [comment]
> @ridhoq can you rebase this? Thanks!

@pxp928 should be good to go now

File: cmd/guacone/cmd/vulnerability.go [hunk 3]
```diff
@@ -117,11 +117,15 @@ var queryVulnCmd = &cobra.Command{
 			if len(vulnResponse.Vulnerabilities) > 0 {
```
Comment (jeffmendoza) [inline cmd/guacone/cmd/vulnerability.go:117]: optional, but putting each side of the `if opts.vulnerabilityID != "" { / else` in its own function would help a lot with the code flow, below. Ex: it's weird to have the `path` variable outside the `if len(vulnResponse.Vulnerabilities) > 0` block. In a function, it could just be:
```go
if len(vulnResponse.Vulnerabilities) == 0 {
    fmt.Printf("Failed to identify vulnerability \n")
    return
}
```

File: cmd/guacone/cmd/vulnerability.go [hunk 4]
```diff
@@ -329,21 +335,23 @@ func searchDependencyPackages(ctx context.Context, gqlclient graphql.Client, top
...
 
+	edgeTypes := []model.Edge{model.EdgeVulnerabilityCertifyVuln, model.EdgeVulnerabilityCertifyVexStatement}
 	for _, vulnerabilitiesResponse := range vulnerabilitiesResponses {
 		for _, vulnerabilityNodeID := range vulnerabilitiesResponse.VulnerabilityIDs {
-			vulnNodeNeighborResponse, err := model.Neighbors(ctx, gqlclient, vulnerabilityNodeID.Id, []model.Edge{edgeType})
+			vulnNodeNeighborResponse, err := model.Neighbors(ctx, gqlclient, vulnerabilityNodeID.Id, edgeTypes)
 
 			if err != nil {
-				return nil, fmt.Errorf("error querying neighbor for vulnerability: %w", err)
+				return nil, []table.Row{}, fmt.Errorf("error querying neighbor for vulnerability: %w", err)
```
Comment (jeffmendoza) [inline cmd/guacone/cmd/vulnerability.go:354]: replace `[]table.Row{}` with `nil` in all the returns. A nil slice is valid, no need to allocated a 0 length slice.

**Review by jeffmendoza — APPROVED** [review]
Looks good, thanks! some minor comments.

**Comment by pxp928** [comment]
FYI @ridhoq made some updates in my PR to the vulnerability query. That will remove unnecessary calls to `neighbors` query: https://github.com/guacsec/guac/pull/1582

File: cmd/guacone/cmd/vulnerability.go (hunk 3 above)
Comment (ridhoq) [reply cmd/guacone/cmd/vulnerability.go]: Took a stab at this in https://github.com/guacsec/guac/pull/1540/commits/4e341e3259518d9d973cacfb11f99250f584fc41. Let me know if I went in the right direction.

**Review by pxp928 — APPROVED** [review]
