### PR TITLE
Fix Logging in Collectsub Server

### LINKED ISSUE #450: Logging not working in collectsub server
The context isn't actually being passed from the `Serve` function and thus the logging introduced in https://github.com/guacsec/guac/pull/436 doesn't actually work. This needs to be fixed so logging works.

### PR DESCRIPTION
**Pull request by arorasoham9**
# Description of the PR

Adds ctx field to collectsub server struct. This way a new context does not need to be passed with every Add/GetCollectEntries call.

Can fix #450

# PR Checklist

- [ ] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Comment by arorasoham9** [comment]
To fix #450, I still need to push another commit that uses the `ctx` field in the collectsub server struct instead of the one passed in as a parameter  in the Serve and Add/GetCollectEntries functions.

File: pkg/collectsub/server/server.go [hunk 1]
```diff
@@ -33,7 +33,9 @@ type server struct {
 	pb.UnimplementedColectSubscriberServiceServer
 
 	// Db points to the backend DB, public for mocking testing purposes.
-	Db   db.CollectSubscriberDb
+	Db db.CollectSubscriberDb
+	// Ctx is the context.Context the server is initialized with
+	Ctx  context.Context
```
Comment (pxp928) [inline pkg/collectsub/server/server.go:38]: there are multiple ways to do this but probably the easiest is to store the logger in the server struct:
```
type server struct {
	pb.UnimplementedColectSubscriberServiceServer

	// Db points to the backend DB, public for mocking testing purposes.
	Db   db.CollectSubscriberDb

	logger *zap.SugaredLogger
	port int
}
``` 

This will allow access to `AddCollectEntries` and `GetCollectEntries` to use the logger from the the server struct `logger := s.logger`. Adding another context will result in confusion about which context is being used.

File: cmd/guaccsub/cmd/root.go [hunk 2]
```diff
@@ -48,6 +48,7 @@ var rootCmd = &cobra.Command{
 			logger.Fatalf("unable to create csub server: %v", err)
 		}
 
+		// csubServer.ctx = ctx
```
Comment (pxp928) [inline cmd/guaccsub/cmd/root.go:51]: in that case, this will not be needed.

File: pkg/collectsub/server/server.go (hunk 1 above)
Comment (lumjjb) [reply pkg/collectsub/server/server.go:38]: i wonder if there's some construct to help set up a connection context for the grpc server

Comment (arorasoham9) [reply pkg/collectsub/server/server.go:38]: @pxp928 Sounds good. I'll make the change.

File: cmd/guaccsub/cmd/root.go (hunk 2 above)
Comment (arorasoham9) [reply cmd/guaccsub/cmd/root.go:51]: Understood. I see how your fix will prevent needing a change to guacsub command.

**Comment by arorasoham9** [comment]
@pxp928 the ctx parameter can be removed from the add/GetEntries functions and a few more places. Otherwise, ready to merge.

**Comment by pxp928** [comment]
@arorasoham9 Apologies but there is a better way to do this. See this article: https://medium.com/hootsuite-engineering/golang-grpc-distributed-context-propagation-5809e2d66db4 under the section "Context Propagation is just the start of the journey". This shows the way to propagate this logger through the ctx. This way, we don't have to pass the logger around.

File: pkg/collectsub/server/server.go (hunk 1 above)
Comment (pxp928) [reply pkg/collectsub/server/server.go]: Based on my quick search yesterday I did not see this article: https://medium.com/hootsuite-engineering/golang-grpc-distributed-context-propagation-5809e2d66db4 but this is the better way to do it as suggested by @lumjjb.

**Comment by arorasoham9** [comment]
@pxp928 No problem. I'll take a look and fix as needed.

**Comment by pxp928** [comment]
@arorasoham9 are you still working on this?

**Comment by arorasoham9** [comment]
@pxp928 Yes! Apologies for the delay. I'll be working on it today.

**Comment by arorasoham9** [comment]
@pxp928 I am a little unsure how to resolve the conflict with the go.mod file. I do need to commit my mod and sum files, correct? I would really appreciate some help. Thanks!

**Comment by pxp928** [comment]
@arorasoham9 you just need to rebase on it on main using:

```
➜  guac git:(collectsub) git remote -v
origin	git@github.com:arorasoham9/guac.git (fetch)
origin	git@github.com:arorasoham9/guac.git (push)
upstream	git@github.com:guacsec/guac.git (fetch)
upstream	git@github.com:guacsec/guac.git (push)
➜  guac git:(collectsub) git pull upstream main --rebase
```

resolve the conflict on your `go.mod` file (can accept both changes) and save it and run `go mod tidy` and that should fix it. 

after that do a `git add .`, `git rebase --continue` and should be all good after that to push.

File: pkg/collectsub/server/server.go [hunk 3]
```diff
@@ -78,13 +83,52 @@ func (s *server) GetCollectEntries(ctx context.Context, in *pb.GetCollectEntries
 	}, nil
 }
 
+func ContextPropagationUnaryServerInterceptor() grpc.UnaryServerInterceptor {
```
Comment (pxp928) [inline pkg/collectsub/server/server.go:86]: lowercase for this

File: pkg/collectsub/server/server.go [hunk 4]
```diff
@@ -78,13 +83,52 @@ func (s *server) GetCollectEntries(ctx context.Context, in *pb.GetCollectEntries
...
+		handler grpc.UnaryHandler,
+	) (interface{}, error) {
+		if md, ok := metadata.FromIncomingContext(ctx); ok {
+			ctx = metadata.NewOutgoingContext(ctx, md)
+		}
+		return handler(ctx, req)
+	}
+}
+
+func ContextToZapFieldsUnaryServerInterceptor() grpc.UnaryServerInterceptor {
```
Comment (pxp928) [inline pkg/collectsub/server/server.go:100]: and this

**Review by pxp928 — APPROVED** [review]
LGTM! Tested this out and it works great! Was able to see the logs coming form the collector subscriber:

```
{"level":"info","ts":1690284770.800513,"caller":"zap/options.go:212","msg":"finished unary call with code OK","grpc.start_time":"2023-07-25T07:32:50-04:00","system":"grpc","span.kind":"server","grpc.service":"guacsec.guac.collect_subscriber.schema.ColectSubscriberService","grpc.method":"AddCollectEntries",":authority":["localhost:2782"],"content-type":["application/grpc"],"user-agent":["grpc-go/1.56.2"],"grpc.code":"OK","grpc.time_ms":0.809}

{"level":"info","ts":1690284775.830697,"caller":"server/server.go:59","msg":"AddCollectEntries called with entries: [type:DATATYPE_PURL  value:\"pkg:deb/debian/base-files@11.1+deb11u4?arch=amd64&distro=debian-11\" type:DATATYPE_PURL  value:\"pkg:golang/k8s.io/release/images/build/go-runner@(devel)\" type:DATATYPE_PURL  value:\"pkg:deb/debian/netbase@6.3?arch=all&distro=debian-11\" type:DATATYPE_PURL  value:\"pkg:deb/debian/tzdata@2021a-1+deb11u4?arch=all&distro=debian-11\" type:DATATYPE_PURL  value:\"pkg:guac/spdx/k8s.gcr.io/kube-scheduler-v1.24.4\"]","grpc.start_time":"2023-07-25T07:32:55-04:00","system":"grpc","span.kind":"server","grpc.service":"guacsec.guac.collect_subscriber.schema.ColectSubscriberService","grpc.method":"AddCollectEntries",":authority":["localhost:2782"],"content-type":["application/grpc"],"user-agent":["grpc-go/1.56.2"]}
```

File: pkg/collectsub/server/server.go (hunk 3 above)
Comment (arorasoham9) [reply pkg/collectsub/server/server.go]: Fixed. Thank you for pointing out.
