### PR TITLE
fix ite6 vuln attestation to use the right predicatetype

### LINKED ISSUE #2188: [ingestion/data-quality issue] Unable to ingest vuln intoto predicate due to guesser failing
**Describe the bug**
When trying to ingest a vuln predicate, we get an error saying it is a generic ITE6, although a parser is implemented. It looks like there's a mismatch within the predicate name (vuln vs vulns).. 

At: https://github.com/guacsec/guac/blob/main/pkg/handler/processor/guesser/type_ite6.go#L42

It should be https://in-toto.io/attestation/vulns/v0.1 instead.

**To Reproduce**

1. Start guacgql
2. Ingest an intoto vuln predicate
3. fail

**Expected behavior**
Successful ingestion. 

**Screenshots**

```
lumb@lumb:~/git/guac$ bin/guacone collect files ~/ssci_metadata/drydock_vuln_single/
{"level":"info","ts":1728584694.8142438,"caller":"logging/logger.go:79","msg":"Logging at info level","guac-version":"v0.9.1"}
{"level":"info","ts":1728584694.814346,"caller":"cli/init.go:65","msg":"Using config file: /usr/local/google/home/lumb/git/guac/guac.yaml","guac-version":"v0.9.1"}
{"level":"error","ts":1728584694.823755,"caller":"collector/collector.go:108","msg":"emit error: unable to ingest document: unable to ingest doc tree: no document parser registered for type: ITE6","guac-version":"v0.9.1","documentHash":"sha256_740e3824ba2ecd1254f307bed4aa93e813e2fd7908c01627dae3a0d76c0f26a1","stacktrace":"github.com/guacsec/guac/pkg/handler/collector.Collect\n\t/usr/local/google/home/lumb/git/guac/pkg/handler/collector/collector.go:108\ngithub.com/guacsec/guac/cmd/guacone/cmd.init.func7\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/cmd/files.go:151\ngithub.com/spf13/cobra.(*Command).execute\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/guacsec/guac/cmd/guacone/cmd.Execute\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/cmd/root.go:57\nmain.main\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/main.go:23\nruntime.main\n\t/usr/lib/google-golang/src/runtime/proc.go:272"}
{"level":"info","ts":1728584694.8239064,"caller":"cmd/files.go:144","msg":"collector ended gracefully","guac-version":"v0.9.1"}
{"level":"fatal","ts":1728584694.8239307,"caller":"cmd/files.go:156","msg":"completed ingestion with error, 0 of 1 were successful - the following files did not ingest successfully:  file:////usr/local/google/home/lumb/ssci_metadata/drydock_vuln_single/vuln.intoto.json","guac-version":"v0.9.1","stacktrace":"github.com/guacsec/guac/cmd/guacone/cmd.init.func7\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/cmd/files.go:156\ngithub.com/spf13/cobra.(*Command).execute\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/usr/local/google/home/lumb/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\ngithub.com/guacsec/guac/cmd/guacone/cmd.Execute\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/cmd/root.go:57\nmain.main\n\t/usr/local/google/home/lumb/git/guac/cmd/guacone/main.go:23\nruntime.main\n\t/usr/lib/google-golang/src/runtime/proc.go:272"}
lumb@lumb:~/git/guac$
```

**GUAC version**
head

**Ingested document(s)**

no:( 

**Additional context**

### PR DESCRIPTION
**Pull request by lumjjb**
# Description of the PR

Fixes #2188 

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [x] All new changes are covered by tests
- [x] If GraphQL schema is changed, `make generate` has been run
- [x] If GraphQL schema is changed, GraphQL client updates/additions have been made
- [x] If OpenAPI spec is changed, `make generate` has been run
- [x] If ent schema is changed, `make generate` has been run
- [x] If `collectsub` protobuf has been changed, `make proto` has been run
- [x] All CI checks are passing (tests and formatting)
- [x] All dependent PRs have already been merged

### CODE REVIEW

File: pkg/handler/processor/guesser/type_ite6.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ func (_ *ite6TypeGuesser) GuessDocumentType(blob []byte, format processor.Format
 				return processor.DocumentITE6Generic
 			} else if strings.HasPrefix(statement.PredicateType, "https://in-toto.io/attestation/certify/v0.1") {
 				return processor.DocumentITE6Generic
-			} else if strings.HasPrefix(statement.PredicateType, "https://in-toto.io/attestation/vuln/v0.1") {
+			} else if strings.HasPrefix(statement.PredicateType, "https://in-toto.io/attestation/vulns/v0.1") {
```
Comment (pxp928) [inline pkg/handler/processor/guesser/type_ite6.go:42]: it will also have to be changed here: https://github.com/guacsec/guac/blob/main/pkg/certifier/attestation/attestation_vuln.go#L30

Until we use the upstream attestation....

Comment (lumjjb) [reply pkg/handler/processor/guesser/type_ite6.go:42]: it looks like [intoto gol](https://github.com/in-toto/in-toto-golang/tree/master/in_toto) needs to be updated to include the predicate as well?

Comment (lumjjb) [reply pkg/handler/processor/guesser/type_ite6.go:42]: oh it looks like there's the other repo https://github.com/in-toto/attestation/tree/main/go/predicates..

Comment (lumjjb) [reply pkg/handler/processor/guesser/type_ite6.go:42]: can i follow up with these changes in a separate PR? i'd like to get at least the flow to the parser first.. thoughts?

**Review by pxp928 — APPROVED** [review]

**Review by mihaimaruseac — APPROVED** [review]
