### PR TITLE
CycloneDX SBOM: support nested components

### LINKED ISSUE #2155: [ingestion/data-quality issue] CycloneDX SBOM with nested components fails ingestion
**Describe the bug**
When ingesting a CycloneDX SBOM with nested components only the outer one is ingested into Guac

**To Reproduce**

1. ingest into Guac sample SBOM [example-cdx-nesting2.cdx.json](https://github.com/user-attachments/files/17193624/example-cdx-nesting2.cdx.json)
2. query `packages` and only one package is returned 

**Expected behavior**
Having 3 packages in the response from the query `packages` endpoint

**GUAC version**
Latest commit on `main` branch at this time, i.e. 6ea218b1f654277eb1c331d0cd275c31536be6c9

**Ingested document(s)**

Linked in step 1 in the "To Reproduce" section above

**Additional context**
Nested components are allowed from CycloneDX specifications for multiple versions.
As a reference, check the latest 1.6 spec at https://cyclonedx.org/docs/1.6/json/#components_items

### PR DESCRIPTION
**Pull request by mrizzi**
# Description of the PR

Implemented recursive traversal for nested components in CycloneDX SBOM.

Fixes #2155 

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [x] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If GraphQL schema is changed, GraphQL client updates/additions have been made
- [ ] If OpenAPI spec is changed, `make generate` has been run
- [ ] If ent schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Review by pxp928 — APPROVED** [review]
LGTM! Thanks @mrizzi

File: pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go [hunk 1]
```diff
@@ -250,6 +254,11 @@ func (c *cyclonedxParser) getPackages() error {
 			if err := c.getLicenseInformation(comp); err != nil {
 				return fmt.Errorf("failed to get license information for component package with error: %w", err)
 			}
+
+			err = traverseComponents(c, comp.Components)
```
[the remark this answers is not in the document]
Comment (mihaimaruseac) [reply pkg/ingestor/parser/cyclonedx/parser_cyclonedx.go:258]: +1

**Review by mihaimaruseac — APPROVED** [review]

File: pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go [hunk 2]
```diff
@@ -492,7 +492,31 @@ func Test_cyclonedxParser_getComponentPackages(t *testing.T) {
 				Type: cdx.ComponentTypeFile,
 			}},
 		},
-		wantPurl: "pkg:guac/files/home/work/test/build/webserver",
+		wantPurl: []string{"pkg:guac/files/home/work/test/build/webserver"},
+	}, {
+		name: "nested components",
```
Comment (pxp928) [inline pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go:497]: Could you also add this to the unit test: `Test_cyclonedxParser` so that we can see that the `isDependency` predicates are defined properly per the dependencies defined in the SBOM:


```
"dependencies": [
    {
      "ref": "pkg:oci/mandrel-for-jdk-21-rhel8@sha256%3A41d92dafa5ccbf7f76fa81c5a0e7de83c51166f27bea9b98df018f644016bf04?arch=amd64&os=linux&tag=23.1-13.1724180416",
      "dependsOn": [
        "pkg:rpm/redhat/abattis-cantarell-fonts@0.0.25-6.el8?arch=noarch",
        "pkg:maven/compiler/compiler@23.1.4.0-1-redhat-00001?type=jar"
      ]
    },
    {
      "ref": "pkg:rpm/redhat/abattis-cantarell-fonts@0.0.25-6.el8?arch=noarch",
      "dependsOn": []
    },
    {
      "ref": "pkg:maven/compiler/compiler@23.1.4.0-1-redhat-00001?type=jar",
      "dependsOn": []
    }
  ]
```

Comment (mrizzi) [reply pkg/ingestor/parser/cyclonedx/parser_cyclonedx_test.go:515]: Good point, thanks :+1: 
I've added both `CycloneDX nested components` and `CycloneDX flat components` tests providing in input two SBOMs with the same information: the former with nested components and the latter with a flat array. The relevant part for these tests is that both expected the same `ociComponentsIsDependencyIngests` value for the `IsDependency` field basically ensuring consistency among the two approaches (nested vs flat).

**Comment by mrizzi** [comment]
@pxp928 I need some support with test results sorting because the check for the `IsDependencyIngest` array, from time to time, fails due to wrong sorting.
I can see `isDependencyLess` is in place and part of the `IngestPredicatesCmpOpts` array used when running diff in `Test_cyclonedxParser`: what else should be done to ensure proper data sorting?

**Review by pxp928 — APPROVED** [review]
Thanks @mrizzi !
